# Generated by Django 5.1.5 on 2025-07-01 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=200)),
                ('Last_word', models.CharField(default='run', max_length=1000)),
                ('Last_word_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
